
logging:
  level:
    jdbc:
      audit: off
      resultset: off
      sqltiming: off
    org:
      hibernate: ERROR
      springframework:
        web: error
    root: INFO
  path: /springboot
spring:
  activemq:
    broker-url: failover:(tcp://localhost:61616)
    in-memory: true
    pool:
      enabled: true  
  datasource:
    connection-test-query: '"SELECT 1"'
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: net.sf.log4jdbc.DriverSpy
    hikari:
      #数据库连接最大链接数
      maximum-pool-size: 100
      #数据库超时时间
      idle-timeout: 3000
      #数据库空闲链接
      minimum-idle: 0
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: false
      javax:
        persistence:
          sharedCache:
            mode: ALL
    show-sql: true
  #resources:
    #static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:{spring.upload-dir}
  #thymeleaf:
    #cache: false
    #prefix: classpath:/templates/
#fenix:
  #print-banner: true
  #xml-locations: fenix
debug: true
